<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Genus;

/**
 * GenusNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusNoteRepository extends EntityRepository
{
	/**
	 * 
	 * @param Genus $genus
	 * @return GenusNote[]
	 */
	public function findAllRecentNotesForGenus(Genus $genus)
	{
		return $this->createQueryBuilder('genus_note')
			->andWhere('genus_note.genus = :genus')
			->setParameter('genus', $genus)
			->andWhere('genus_note.createdAt > :recentDate')
			->setParameter('recentDate', new \DateTime('-3 months'))
			->getQuery()
			->execute();
	}
}
