<?php

namespace AppBundle\Repository;

/**
 * SubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticallQueryBuilder()
    {
    	   return $this->createQueryBuilder('sub_family')
    	       ->orderBy('sub_family.name', 'ASC');
    }
}
